### ISSUE TITLE
How to paser latex?

### ISSUE THREAD

**Issue by huge818** [chaosim/peasy#2]
How to paser latex?
example

sqrt  \sqrt{x}
fraction  \frac{1}{2}
sup   x^2

 what is the value of \sqrt{\frac{1}{2}+5^2} ?

**Comment by chaosim** [comment]
I'm not familiar with latex. Please allow me to do some research.
Maybe these two links  below is helpfule?
http://johnmacfarlane.net/pandoc/
http://www.mathjax.org/

**Comment by huge818** [comment]
计算这个表达式跟mathjax没关系的，希望有一个解析latex的一个很好的引擎

 ------------------ 原始邮件 ------------------
  发件人: "chaosim";notifications@github.com;
 发送时间: 2014年1月11日(星期六) 下午4:11
 收件人: "chaosim/peasy"peasy@noreply.github.com; 
 抄送: "传说中的湖"huzc818@qq.com; 
 主题: Re: [peasy] How to paser latex? (#2)

I'm not familiar with latex. Please allow me to do some research.
Maybe these two links below is helpfule?
http://johnmacfarlane.net/pandoc/
http://www.mathjax.org/

**Comment by chaosim** [comment]
很遗憾我现在没有时间完成这个事情。
